// One public-file allowlist shared by the local server and static release builder.
export const PUBLIC_ASSETS = Object.freeze({ 'index.html': 'text/html', 'app.mjs': 'text/javascript', 'style-switcher.mjs': 'text/javascript', 'atelier.css': 'text/css', 'atelier.mjs': 'text/javascript', 'online-store.mjs': 'text/javascript', 'profile-portability.mjs': 'text/javascript', 'profile-brief.mjs': 'text/javascript', 'calendar.mjs': 'text/javascript', 'style.css': 'text/css', 'matching.mjs': 'text/javascript',
  'onboarding-tour.mjs': 'text/javascript',
  'location-session.mjs': 'text/javascript',
  'demo-journey.mjs': 'text/javascript',
  'summit.html': 'text/html', 'summit.css': 'text/css', 'summit.mjs': 'text/javascript',
  'get.html': 'text/html', 'product-access.mjs': 'text/javascript',
  'triangle.html': 'text/html', 'triangle.css': 'text/css', 'triangle.mjs': 'text/javascript',
  'triangle-room.mjs': 'text/javascript', 'explore-planner.mjs': 'text/javascript',
  'studio.html': 'text/html', 'studio.css': 'text/css', 'studio.mjs': 'text/javascript',
  'studio-journey.html': 'text/html', 'journey.css': 'text/css', 'journey-ui.mjs': 'text/javascript',
  'journey-core.mjs': 'text/javascript', 'journey-ai-client.mjs': 'text/javascript', 'journey-handoff.mjs': 'text/javascript',
  'rooms.html': 'text/html', 'rooms.css': 'text/css', 'rooms.mjs': 'text/javascript', 'room-api.mjs': 'text/javascript',
  'studio-install.mjs': 'text/javascript', 'studio-sw.mjs': 'text/javascript', 'studio.webmanifest': 'application/manifest+json',
  'session-value.mjs': 'text/javascript', 'declared-fit.mjs': 'text/javascript', 'group-logistics.mjs': 'text/javascript', 'archive-codec.mjs': 'text/javascript',
  'profile-store.mjs': 'text/javascript', 'neon-store.mjs': 'text/javascript', 'chatgpt-transfer.mjs': 'text/javascript',
  'map.mjs': 'text/javascript', 'pilot-policy.mjs': 'text/javascript', 'profile-package.mjs': 'text/javascript', 'business-case.mjs': 'text/javascript', 'profile-import.mjs': 'text/javascript',
  'i18n.mjs': 'text/javascript', 'proof-state.mjs': 'text/javascript', 'need-decay.mjs': 'text/javascript', 'meeting-card.mjs': 'text/javascript', 'live-location.mjs': 'text/javascript', 'meeting-location.mjs': 'text/javascript',
  'cycle-exchange.mjs': 'text/javascript', 'b-matching.mjs': 'text/javascript', 'field-audience.mjs': 'text/javascript',
  'swiss-compliance.mjs': 'text/javascript',
  'funnel-analytics.mjs': 'text/javascript',
  'manifest.webmanifest': 'application/manifest+json', 'pwa.mjs': 'text/javascript', 'sw.mjs': 'text/javascript',
  'legal.html': 'text/html', 'catalogue.html': 'text/html', 'icon-192.png': 'image/png', 'icon-512.png': 'image/png', 'apple-touch-icon.png': 'image/png',
  'tokens.css': 'text/css', 'montserrat-400.woff2': 'font/woff2', 'montserrat-500.woff2': 'font/woff2', 'cascade.mjs': 'text/javascript', 'iceberg-client.mjs': 'text/javascript'
});
