import { NeonStore } from './neon-store.mjs';
import { ServiceError } from './profile-store.mjs';
import { RoomApi, assertRoomGate } from './room-api.mjs';

const $ = selector => document.querySelector(selector);
const demoEnabled = false; // This route never synthesizes participants or a transcript.
let api, store, own, rooms = [], selected = null, poll = null, polling = false, pendingMessage = null, viewEpoch = 0;
// Keep only canonical server fields. In particular, a transcript is never retained for an invited/left member.
function detail(value) {
  const raw = value?.room ?? value;
  if (!raw || typeof raw !== 'object') return null;
  const membership = clean(raw.own_membership_status);
  return { id:clean(raw.id), title:clean(raw.title), goal:clean(raw.goal), status:clean(raw.status), revision:raw.revision,
    server_now:clean(raw.server_now), own_role:clean(raw.own_role), own_membership_status:membership,
    participants:Array.isArray(raw.participants) ? raw.participants.map(person => ({ user_id:clean(person?.user_id), role:clean(person?.role), membership_status:clean(person?.membership_status), position:person?.position, display_name:clean(person?.display_name) })) : [],
    active_turn:raw.active_turn && typeof raw.active_turn === 'object' ? { speaker_id:clean(raw.active_turn.speaker_id), deadline:clean(raw.active_turn.deadline) } : null,
    transcript:membership === 'accepted' && Array.isArray(raw.transcript) ? raw.transcript.map(message => ({ message_id:clean(message?.message_id), sender_id:clean(message?.sender_id), room_revision:message?.room_revision, body:clean(message?.body), created_at:clean(message?.created_at) })) : [],
    last_turn_event:raw.last_turn_event && typeof raw.last_turn_event === 'object' ? { kind:clean(raw.last_turn_event.kind), created_at:clean(raw.last_turn_event.created_at) } : null };
}
const listValue = value => (Array.isArray(value) ? value : []).map(detail).filter(Boolean);
const setStatus = value => { $('#rooms-status').textContent = value || ''; };
const clean = value => typeof value === 'string' ? value : '';
const ownId = () => own?.id || store?.user?.id;
function formatDate(value) { const date = new Date(value); return Number.isFinite(date.valueOf()) ? date.toLocaleString('uk-UA', { dateStyle:'short', timeStyle:'short' }) : ''; }
function isAccepted(room) { return room?.participants?.length > 1 && room.participants.every(person => person.membership_status === 'accepted'); }
function current(room) { return room?.participants?.find(person => person.user_id === room.active_turn?.speaker_id) || null; }
function isMyTurn(room) { return room?.status === 'active' && room?.active_turn?.speaker_id === ownId(); }
function deadlinePassed(room) { return Boolean(room?.active_turn?.deadline && room?.server_now && Date.parse(room.active_turn.deadline) <= Date.parse(room.server_now)); }
function canAdvance(room) { return room?.status === 'active' && room?.own_membership_status === 'accepted' && (isMyTurn(room) || deadlinePassed(room)); }
function roomState(room) { return ({ inviting:'Запрошення очікують', active:'Кімната активна', paused:'Кімната призупинена', closed:'Кімната закрита' })[room?.status] || 'Стан оновлюється'; }
function setBlocked(copy) { $('#rooms-blocked-copy').textContent = copy; $('#rooms-blocked').hidden = false; }
function stopPolling() { if (poll) clearInterval(poll); poll = null; }
function startPolling() { stopPolling(); if (!selected || document.hidden) return; poll = setInterval(() => { refreshSelected().catch(handleError); }, 5000); }
function clearPrivateDom() { $('#room-message').value = ''; $('#room-messages').replaceChildren(); $('#room-title').textContent = ''; $('#room-goal').textContent = ''; pendingMessage = null; }
async function refreshSelected(force = false) { if (!selected || (!force && document.hidden) || polling) return; const id = selected.id, epoch = viewEpoch; polling = true; try { const next = detail(await api.get(id)); if (selected?.id !== id || viewEpoch !== epoch) return; selected = next; renderRoom(); } finally { polling = false; } }
function element(tag, text, className) { const node = document.createElement(tag); if (text !== undefined) node.textContent = text; if (className) node.className = className; return node; }
function updateIndex() { const index = $('#rooms-index'); index.replaceChildren(); if (!rooms.length) { index.append(element('p', 'Поки немає запрошень або кімнат.', 'rooms-empty')); return; } for (const room of rooms) { const button = element('button'); button.type = 'button'; button.setAttribute('aria-current', String(selected?.id === room.id)); button.append(element('b', clean(room.title) || 'Кімната'), element('small', roomState(room))); button.addEventListener('click', () => openRoom(room.id)); index.append(button); } }
function renderPeople(profiles) { const host = $('#rooms-people'); host.replaceChildren(); for (const profile of profiles) { if (!profile?.id || profile.id === ownId() || !clean(profile.display_name)) continue; const label = element('label', undefined, 'rooms-person'); const input = element('input'); input.type = 'checkbox'; input.name = 'invitee'; input.value = profile.id; const name = element('span', profile.display_name); input.addEventListener('change', previewCreate); label.append(input, name); host.append(label); } if (!host.children.length) host.append(element('p', 'Немає доступних профілів для запрошення.', 'rooms-empty')); }
function previewCreate() { const form = $('#rooms-create-form'), chosen = [...form.querySelectorAll('input[name=invitee]:checked')]; const preview = $('#rooms-preview'); if (chosen.length < 1 || chosen.length > 2) { preview.hidden = true; return; } const names = chosen.map(input => input.closest('label').textContent.trim()).join(', '); preview.textContent = `Запрошення отримають: ${names}. Назва та ціль залишаться лише в пам’яті цієї вкладки до надсилання.`; preview.hidden = false; }
function memberLabel(person) { return clean(person?.display_name) || (person?.role === 'creator' ? 'Автор кімнати' : 'Учасник'); }
function renderRoom() { const room = selected; $('#rooms-detail').hidden = !room; $('#rooms-create').hidden = Boolean(room); if (!room) return; $('#room-title').textContent = clean(room.title); $('#room-goal').textContent = clean(room.goal); $('#room-state').textContent = `${roomState(room)} · твоя участь: ${({ invited:'запрошення', accepted:'прийнято', left:'вийшов/вийшла', revoked:'відкликано' })[room.own_membership_status] || 'невідома'}`; const seats = [$('#seat-0'), $('#seat-1'), $('#seat-2')]; const people = [...room.participants].sort((left, right) => left.position - right.position); seats.forEach((seat, i) => { const person = people[i]; seat.replaceChildren(); seat.dataset.current = String(person?.user_id === room.active_turn?.speaker_id); seat.append(element('b', memberLabel(person)), element('small', ({ accepted:'прийнято', invited:'очікує', left:'вийшов/вийшла', revoked:'відкликано' })[person?.membership_status] || 'стан невідомий')); }); const speaker = current(room); const deadline = formatDate(room.active_turn?.deadline); const event = room.last_turn_event?.kind === 'no_response' ? ' Попередня черга минула без повідомлення; це не згода.' : ''; $('#room-turn-note').textContent = room.status === 'active' ? (speaker ? `Зараз слово має ${memberLabel(speaker)}.${deadline ? ` Орієнтир сервера: ${deadline}.` : ''}${event}` : 'Черга оновлюється.') : isAccepted(room) && room.status === 'inviting' ? 'Усі учасники прийняли запрошення. Автор кімнати може почати текстову чергу.' : room.own_membership_status === 'invited' ? 'Прочитай ціль вище й обери «Прийняти запрошення» лише якщо хочеш увійти.' : 'Кімната не активна.';
  const actions = $('#room-actions'); actions.replaceChildren(); if (room.own_membership_status === 'invited' && room.status === 'inviting') addAction(actions, 'Прийняти запрошення', () => api.accept(room.id)); if (room.own_membership_status === 'invited') addAction(actions, 'Відхилити запрошення', () => api.leave(room.id), 'rooms-danger'); if (room.own_membership_status === 'accepted' && room.status !== 'closed') addAction(actions, 'Вийти з кімнати', () => api.leave(room.id), 'rooms-danger'); if (room.own_role === 'creator' && isAccepted(room) && room.status === 'inviting') addAction(actions, 'Почати чергу', () => api.start(room.id, room.revision)); const editable = isMyTurn(room); $('#room-message').disabled = !editable; $('#room-send').disabled = !editable; $('#room-pass').disabled = !canAdvance(room); $('#room-message').setAttribute('aria-describedby', 'room-turn-note'); $('#room-close').disabled = room.status === 'closed' || room.own_role !== 'creator' || room.own_membership_status !== 'accepted'; renderMessages(room); }
function addAction(host, label, action, className = 'rooms-quiet') { const button = element('button', label, className); button.type = 'button'; button.addEventListener('click', () => runAction(action)); host.append(button); }
function renderMessages(room) { const host = $('#room-messages'); host.replaceChildren(); const messages = room.own_membership_status === 'accepted' ? room.transcript : []; if (!messages.length) { host.append(element('p', room.own_membership_status === 'accepted' ? 'Поки немає тексту в кімнаті.' : 'Текст кімнати стане видимим лише після прийняття запрошення.', 'rooms-empty')); return; } for (const message of messages) { const person = room.participants?.find(item => item.user_id === message.sender_id); const article = element('article', undefined, 'rooms-message'); article.append(element('b', memberLabel(person)), element('p', clean(message.body)), element('time', formatDate(message.created_at))); host.append(article); } }
async function openRoom(id) { try { viewEpoch++; if (selected?.id !== id) clearPrivateDom(); selected = detail(await api.get(id)); renderRoom(); updateIndex(); startPolling(); } catch (error) { handleError(error); } }
async function reloadRooms() { rooms = listValue(await api.list()); updateIndex(); if (selected) { const found = rooms.find(room => room.id === selected.id); if (found) await refreshSelected(true); else { viewEpoch++; selected = null; clearPrivateDom(); renderRoom(); stopPolling(); } } }
async function runAction(action) { try { const result = detail(await action()); if (result?.id) selected = result; await reloadRooms(); renderRoom(); startPolling(); } catch (error) { handleError(error); } }
function handleError(error) { if (error instanceof ServiceError && error.status === 401) { viewEpoch++; stopPolling(); selected = null; clearPrivateDom(); $('#rooms-app').hidden = true; $('#rooms-auth').hidden = false; setStatus('Сесію завершено. Увійди ще раз.'); return; } if (error instanceof ServiceError && error.status === 403) { viewEpoch++; stopPolling(); selected = null; clearPrivateDom(); renderRoom(); setStatus('Ця приватна кімната більше недоступна.'); return; } if (error instanceof ServiceError && error.status === 409) { setStatus('Стан кімнати змінився. Оновлюю його; чернетка лишилась у полі.'); refreshSelected().catch(() => {}); return; } setStatus(error?.message || 'Не вдалося оновити кімнату.'); }
$('#rooms-refresh').addEventListener('click', () => reloadRooms().catch(handleError));
$('#rooms-create-form').addEventListener('submit', event => { event.preventDefault(); const form = event.currentTarget, invitee_ids = [...form.querySelectorAll('input[name=invitee]:checked')].map(input => input.value); runAction(async () => { const result = await api.create({ title: form.elements.title.value, goal: form.elements.goal.value, invitee_ids }); form.reset(); $('#rooms-preview').hidden = true; return result; }); });
$('#room-message-form').addEventListener('submit', event => { event.preventDefault(); const body = $('#room-message').value; if (!selected || !isMyTurn(selected)) return; if (!pendingMessage || pendingMessage.body !== body || pendingMessage.revision !== selected.revision) pendingMessage = { body, revision: selected.revision, id: crypto.randomUUID() }; runAction(async () => { const result = await api.message(selected.id, { expected_revision: pendingMessage.revision, message_id: pendingMessage.id, body: pendingMessage.body }); $('#room-message').value = ''; pendingMessage = null; return result; }); });
$('#room-pass').addEventListener('click', () => { if (selected) runAction(() => api.advance(selected.id, selected.revision)); });
$('#room-close').addEventListener('click', () => { if (selected) runAction(() => api.close(selected.id, selected.revision)); });
$('#room-l').addEventListener('click', () => { if (selected) setStatus($('#room-turn-note').textContent); });
document.addEventListener('visibilitychange', () => { if (document.hidden) stopPolling(); else { refreshSelected().catch(handleError); startPolling(); } });
async function init() { try { const configResponse = await fetch('/config.json', { cache:'no-store' }); if (!configResponse.ok) throw new Error(); const config = await configResponse.json(); try { assertRoomGate(config); } catch { setBlocked(demoEnabled ? 'Демо-режим не показує людей або повідомлення.' : 'Пілотна мережна кімната ще не ввімкнена. Можна відкрити локальний Studio.'); return; } store = new NeonStore(config); if (!await store.restore()) { $('#rooms-auth').hidden = false; return; } if (!await store.hasPolicy()) { setBlocked('Для кімнат потрібне чинне підтвердження правил пілоту у власному профілі.'); return; } own = await store.ownProfile(); api = new RoomApi(store, config); const profiles = await store.discover(); renderPeople(profiles); $('#rooms-app').hidden = false; await reloadRooms(); } catch (error) { setBlocked(error?.message || 'Не вдалося перевірити захищену конфігурацію кімнати. Спробуй пізніше або відкрий Studio.'); } }
init();
