import {createSession,confirmOutcome,revokeOutcomeConfirmation,replaceOutcome,sessionConfirmationStatus,createSocialDraft,archiveSession,importSessionArchive,searchArchiveExactQuote} from './session-value.mjs';
import {explainDeclaredFit} from './declared-fit.mjs';
import {createLogistics,reviseLogistics,recordLogisticsPreference,resolveLogistics} from './group-logistics.mjs';
import {packArchive,unpackArchive} from './archive-codec.mjs';
import {takeJourneyHandoff} from './journey-handoff.mjs';
const $=selector=>document.querySelector(selector),all=selector=>[...document.querySelectorAll(selector)];
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function announce(text){$('#value-status').textContent=text;}
async function guard(action){try{await action();}catch(error){announce(error.message||'Не вдалося виконати дію.');}}
let session=null,names={},logistics=null,social=null,pendingArchive=null;
const labels={code:'Код',automation:'Код / автоматизація',design:'Дизайн',sales:'Продажі',matched:'збігається',unknown:'ще невідомо',mismatch:'потребує уточнення'};
const uid=prefix=>prefix+'-'+crypto.randomUUID();
function requireSession(){if(!session)throw new Error('Спочатку почни сесію на етапі 02.');}
function archive(){requireSession();return archiveSession(session,{archiveId:session.sessionId,createdAt:Date.now()});}
function acceptedArchive(){return importSessionArchive(archive());}
const pendingOutcome=()=>session?.outcome.facts.some(f=>f.sourceId==='pending');
function step(name){if(!['fit','session','value','memory'].includes(name))name='fit';for(const n of all('[data-step]'))n.setAttribute('aria-pressed',String(n.dataset.step===name));for(const n of all('main>.studio-pane'))n.hidden=n.id!==`step-${name}`;history.replaceState(null,'',`#${name}`);announce('');}
for(const button of all('[data-step]'))button.addEventListener('click',()=>step(button.dataset.step));
for(const button of all('[data-go]'))button.addEventListener('click',()=>step(button.dataset.go));step(location.hash.slice(1));
const fixture=(id,gives,needs,communication,lang=['en','de'])=>({id,publicVisibility:true,fitConsent:true,gives,needs,languages:lang,modes:['exchange'],timePreferences:['weekday_evening'],preferences:{communication:{enabled:true,values:[communication]},work:{enabled:false,values:[]}}});
const candidates=[{name:'Mara · вигаданий профіль',profile:fixture('mara',['design'],['automation'],'in_person')},{name:'Noor · вигаданий профіль',profile:fixture('noor',['automation'],['sales'],'async')},{name:'Leo · вигаданий профіль',profile:fixture('leo',['sales'],['design'],'video')}];
$('#fit-form').addEventListener('submit',event=>{event.preventDefault();guard(()=>{
 const skill=id=>$(id).value==='code'?'automation':$(id).value;
 const mine={...fixture('you',[skill('#fit-give')],[skill('#fit-need')],$('#fit-communication').value,[$('#fit-language').value]),fitConsent:$('#fit-consent').checked,publicVisibility:$('#fit-public').checked};
 const target=$('#fit-results');target.replaceChildren();
 if(!mine.fitConsent||!mine.publicVisibility){target.append(el('article',!mine.fitConsent?'Порівняння вимкнено. Сам обери, чи враховувати побажання.':'Приватний дозвіл не відкриває профіль на спільному екрані. Видимість обирається окремо.','studio-card'));return;}
 for(const candidate of candidates){const result=explainDeclaredFit(mine,candidate.profile);if(result.status!=='explained')continue;const card=el('article',undefined,'studio-card'),e=result.explanation;card.append(el('h3',candidate.name));const list=el('ul');
 list.append(el('li',`Ти отримуєш: ${e.complementarity.toA.tags.map(t=>labels[t]||t).join(', ')||labels[e.complementarity.toA.status]}.`),el('li',`Ти даєш: ${e.complementarity.toB.tags.map(t=>labels[t]||t).join(', ')||labels[e.complementarity.toB.status]}.`));
 for(const [dimension,title]of[['language','Мова'],['communication','Спілкування'],['work','Стиль роботи']])list.append(el('li',`${title}: ${labels[e.preferences[dimension].status]}.`));card.append(list,el('p','Інтерес і реальна компетентність ще потребують особистої розмови.','subtle'));const conversation=el('a',`Почати розмову з ${candidate.profile.id} ↗`,'primary');conversation.href='/studio-journey.html?person='+encodeURIComponent(candidate.profile.id);card.append(conversation);target.append(card);}
});});
$('#participant-count').addEventListener('change',()=>{$('#participant-c-field').hidden=$('#participant-count').value==='2';$('#participant-c').required=$('#participant-count').value==='3';});
$('#session-setup').addEventListener('submit',event=>{event.preventDefault();guard(()=>{
 if(session&&!confirm('Почати нову сесію? Спочатку експортуй або збережи попередню.'))return;
 const participantIds=['a','b','c'].slice(0,Number($('#participant-count').value)),now=Date.now();names=Object.fromEntries(participantIds.map(id=>[id,$(`#participant-${id}`).value.trim()]));
 if(Object.values(names).some(n=>!n)||new Set(Object.values(names)).size!==participantIds.length)throw new Error('Вкажи різні імена учасників.');
 session=createSession({sessionId:uid('session'),participantIds,notes:[{sourceId:'goal',text:$('#session-goal').value,at:now},...participantIds.map(id=>({sourceId:`member-${id}`,text:names[id],at:now}))],outcome:{revision:1,facts:[{sourceId:'pending',text:'Результат ще не внесено.'}]}});logistics=null;social=null;renderSession();renderLogistics();renderOutcome();announce('Сесію створено. Нотатки залишаються в цій вкладці до явного збереження.');
});});
function renderSession(){if(!session)return;$('#session-work').hidden=false;$('#active-session-goal').textContent=session.notes.find(n=>n.sourceId==='goal')?.text||'Відкрита сесія';$('#note-member').replaceChildren();
 for(const id of session.participantIds){const option=el('option',names[id]||id);option.value=id;$('#note-member').append(option);}
 const target=$('#session-notes');target.replaceChildren();for(const note of session.notes.filter(n=>!['goal',...session.participantIds.map(id=>`member-${id}`)].includes(n.sourceId))){const card=el('article');card.append(el('b',`${names[note.sourceId.split('.')[0]]||'Нотатка'} · ${new Date(note.at).toLocaleTimeString()}`),el('p',note.text));target.append(card);}
}
$('#note-form').addEventListener('submit',event=>{event.preventDefault();guard(()=>{requireSession();const note={sourceId:`${$('#note-member').value}.${uid('note')}`,text:$('#note-text').value,at:Date.now()};session=importSessionArchive(archiveSession({...session,notes:[...session.notes,note]},{archiveId:session.sessionId,createdAt:Date.now()})).session;$('#note-text').value='';renderSession();announce('Оригінальні слова збережено в поточній сесії.');});});
const localDate=time=>{const d=new Date(time);return new Date(time-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
$('#logistics-when').value=localDate(Date.now()+86400000);$('#logistics-deadline').value=localDate(Date.now()+3600000);
$('#logistics-form').addEventListener('submit',event=>{event.preventDefault();guard(()=>{requireSession();const input={place:$('#logistics-place').value,when:new Date($('#logistics-when').value).toISOString(),deadline:new Date($('#logistics-deadline').value).getTime()};logistics=logistics?reviseLogistics(logistics,input):createLogistics(session.participantIds,input);renderLogistics();});});
function renderLogistics(){const target=$('#logistics-votes');target.replaceChildren();if(!logistics)return;target.append(el('p',`Версія ${logistics.proposal.revision}: ${logistics.proposal.place} · ${new Date(logistics.proposal.when).toLocaleString()}`));const state=el('p',undefined,'result-state');state.id='logistics-state';state.setAttribute('role','status');target.append(state);
 for(const id of session.participantIds){const row=el('div',undefined,'member-action');row.append(el('b',names[id]||id));const buttons=el('div',undefined,'button-row');for(const [choice,title]of[['yes','Так'],['no','Ні'],['withdraw','Відкликати відповідь']]){const b=el('button',title);b.type='button';b.addEventListener('click',()=>guard(()=>{logistics=recordLogisticsPreference(logistics,id,choice);renderLogistics();}));buttons.append(b);}row.append(buttons);
 const label=el('label','Резервна відповідь після дедлайну'),select=el('select');select.setAttribute('aria-label',`Резервна відповідь ${names[id]||id}`);for(const [value,title]of[['withdraw','Без резервної відповіді'],['yes','Заздалегідь обираю «так»'],['no','Заздалегідь обираю «ні»']]){const o=el('option',title);o.value=value;select.append(o);}select.value=logistics.fallbacks[id]?.choice||'withdraw';label.append(select);const save=el('button','Зберегти мій резервний вибір');save.type='button';save.addEventListener('click',()=>guard(()=>{logistics=recordLogisticsPreference(logistics,id,select.value,Date.now(),true);renderLogistics();}));row.append(label,save);target.append(row);}
 updateLogistics();}
function updateLogistics(){if(!logistics)return;const r=resolveLogistics(logistics),titles={all_prefer_yes:'Усі обрали «так» для планування. Участь ще не підтверджено.',declined:'Є «ні». Уточніть місце або час.',awaiting:'Очікуємо власних відповідей.',expired_incomplete:'Дедлайн минув; не всі відповіли.'};const p=$('#logistics-state');p.textContent=titles[r.status]+' '+r.responses.map(v=>`${names[v.id]||v.id}: ${v.choice===null?'без відповіді':v.choice==='yes'?'так':'ні'}${v.source==='preselected_fallback'?' (попередній резервний вибір)':''}`).join(' · ');p.dataset.state=r.status;for(const b of all('#logistics-votes button'))b.disabled=Date.now()>=logistics.proposal.deadline;}
setInterval(updateLogistics,1000);
$('#outcome-form').addEventListener('submit',event=>{event.preventDefault();guard(()=>{requireSession();const lines=$('#outcome-facts').value.split('\n').filter(s=>s.trim());if(!lines.length)throw new Error('Внеси хоча б один факт.');session=replaceOutcome(session,{outcome:{revision:session.outcome.revision+1,facts:lines.map(text=>({sourceId:uid('fact'),text}))},at:Date.now()});social=null;renderOutcome();announce('Нова версія результату. Попередні підтвердження очищено.');});});
function clearSocial(){social=null;$('#social-preview').textContent='Підтвердьте поточний результат.';$('#social-sources').replaceChildren();$('#copy-social').disabled=true;$('#download-card').disabled=true;}
function renderOutcome(){clearSocial();const target=$('#outcome-confirmations');target.replaceChildren();if(!session){$('#make-social').disabled=true;return;}target.append(el('p',`Версія ${session.outcome.revision}`));if(pendingOutcome()){target.append(el('p','Спочатку внеси реальний результат.','subtle'));$('#make-social').disabled=true;return;}
 const facts=el('ul');for(const f of session.outcome.facts)facts.append(el('li',f.text));target.append(facts);
 for(const id of session.participantIds){const row=el('div',undefined,'member-action'),confirmed=Object.hasOwn(session.confirmations,id),b=el('button',confirmed?`Відкликати: ${names[id]||id}`:`Підтверджую: ${names[id]||id}`);b.type='button';b.dataset.confirm=id;b.addEventListener('click',()=>guard(()=>{session=confirmed?revokeOutcomeConfirmation(session,{participantId:id,at:Date.now()}):confirmOutcome(session,{participantId:id,revision:session.outcome.revision,at:Date.now()});renderOutcome();}));row.append(b,el('p',confirmed?'Підтвердив/-ла цю версію на спільному екрані.':'Потрібне власне явне підтвердження.'));target.append(row);}
 const status=sessionConfirmationStatus(session);$('#make-social').disabled=status.status!=='confirmed_same_device_unverified';target.append(el('p',status.missingParticipantIds.length?`Ще без відповіді: ${status.missingParticipantIds.map(id=>names[id]||id).join(', ')}.`:'Усі локальні підтвердження є. Чернетку можна підготувати.','result-state'));
}
$('#make-social').addEventListener('click',()=>guard(()=>{requireSession();if(pendingOutcome())throw new Error('Спочатку внеси реальний результат.');social=createSocialDraft(session,{wording:$('#social-wording').value});$('#social-preview').textContent=social.text;$('#social-sources').replaceChildren(...social.sourceReferences.map(s=>el('li',`${s.sourceId} → ${s.locator}`)));$('#copy-social').disabled=false;$('#download-card').disabled=false;}));
$('#social-wording').addEventListener('change',clearSocial);
$('#copy-social').addEventListener('click',()=>guard(async()=>{if(!social)throw new Error('Чернетки ще немає.');await navigator.clipboard.writeText(social.text);announce('Чернетку скопійовано. Перевір її перед власною публікацією.');}));
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const escapeXML=value=>value.replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
$('#download-card').addEventListener('click',()=>guard(()=>{if(!social)throw new Error('Чернетки ще немає.');const facts=session.outcome.facts;const lines=[];for(const fact of facts){const chars=Array.from(fact.text);for(let i=0;i<chars.length;i+=58)lines.push(chars.slice(i,i+58).join(''));lines.push('');}const height=Math.max(600,250+lines.length*30);const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="${height}" viewBox="0 0 1200 ${height}"><rect width="1200" height="${height}" fill="#111b16"/><text x="70" y="90" fill="#d5b585" font-family="sans-serif" font-size="36">synera · session notes</text><text x="70" y="140" fill="#b8d8d0" font-family="sans-serif" font-size="20">Локальна неперевірена сесія · версія ${session.outcome.revision}</text>${lines.map((line,i)=>`<text x="70" y="${210+i*30}" fill="#ececde" font-family="sans-serif" font-size="24">${escapeXML(line)}</text>`).join('')}</svg>`;download(svg,'synera-session-card.svg','image/svg+xml');announce('Картку створено лише з ваших фактів. Перевір її перед поширенням.');}));
$('#copy-invite').addEventListener('click',()=>guard(async()=>{await navigator.clipboard.writeText(new URL('/studio.html',location.origin).href);announce('Публічне посилання скопійовано. Воно не дає доступу до твоєї сесії.');}));
$('#export-session').addEventListener('click',()=>guard(async()=>{const result=await packArchive(archive(),$('#archive-gzip').checked);download(result.json,'synera-session-archive.json','application/json');$('#archive-stats').textContent=`Оригінал: ${result.originalBytes} байт · payload: ${result.payloadBytes} · весь файл із SHA-256: ${result.envelopeBytes}. Економію API-токенів це не доводить.`;}));
$('#archive-file').addEventListener('change',()=>guard(async()=>{pendingArchive=null;$('#archive-preview').hidden=true;const file=$('#archive-file').files[0];if(!file)return;if(file.size>1.5*1024*1024)throw new Error('Файл завеликий.');pendingArchive=importSessionArchive(await unpackArchive(await file.text()));$('#archive-summary').textContent=`Перевірена структура й цілісність. ${pendingArchive.session.participantIds.length} учасники, ${pendingArchive.session.notes.length} нотаток, версія ${pendingArchive.session.outcome.revision}. Особи й правдивість фактів не засвідчені.`;$('#archive-preview').hidden=false;}));
function openArchive(value){if(session&&!confirm('Відкрити іншу сесію? Незбережена поточна сесія буде замінена у вкладці.'))return;session=value.session;names=Object.fromEntries(session.participantIds.map(id=>[id,session.notes.find(n=>n.sourceId===`member-${id}`)?.text||id]));logistics=null;social=null;$('#outcome-facts').value=pendingOutcome()?'':session.outcome.facts.map(f=>f.text).join('\n');renderSession();renderOutcome();renderLogistics();step('session');announce('Власний архів відкрито. Нових дозволів і публікацій не виконано.');}
$('#accept-archive').addEventListener('click',()=>guard(()=>{if(!pendingArchive)throw new Error('Спочатку перевір файл.');openArchive(pendingArchive);}));
function openDatabase(){return new Promise((resolve,reject)=>{const request=indexedDB.open('synera-studio-v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('sessions',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(new Error('Сховище браузера недоступне. Експортуй файл.'));});}
async function deviceOperation(mode,action){const db=await openDatabase();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('sessions',mode),store=tx.objectStore('sessions');let result;const request=action(store);request.onsuccess=()=>{result=request.result;};tx.oncomplete=()=>resolve(result);tx.onerror=tx.onabort=()=>reject(new Error('Не вдалося зберегти/прочитати сесію.'));});}finally{db.close();}}
$('#save-device').addEventListener('click',()=>guard(async()=>{requireSession();if(!$('#device-consent').checked)throw new Error('Для збереження потрібен твій явний вибір.');const rows=await deviceOperation('readonly',store=>store.getAll());if(rows.length>=20&&!rows.some(r=>r.id===session.sessionId))throw new Error('Збережено 20 сесій. Експортуй і видали зайву копію.');const snapshot=archive();await deviceOperation('readwrite',store=>store.put({id:session.sessionId,at:Date.now(),json:snapshot}));announce('Сесію збережено лише у браузері цього пристрою. Автозбереження не ввімкнено.');}));
$('#list-device').addEventListener('click',()=>guard(listDevice));
async function listDevice(){const rows=await deviceOperation('readonly',store=>store.getAll()),target=$('#device-sessions');target.replaceChildren();if(!rows.length){target.append(el('p','Поки що немає збережених сесій.'));return;}for(const row of rows.sort((a,b)=>b.at-a.at)){let value;try{value=importSessionArchive(row.json);}catch{target.append(el('p','Пошкоджену сесію не відкрито.'));continue;}const card=el('div',undefined,'saved-session');card.append(el('p',value.session.notes.find(n=>n.sourceId==='goal')?.text||value.archiveId));const buttons=el('div',undefined,'button-row'),open=el('button','Відкрити'),remove=el('button','Видалити копію з пристрою');open.type=remove.type='button';open.addEventListener('click',()=>guard(()=>openArchive(value)));remove.addEventListener('click',()=>guard(async()=>{if(!confirm('Видалити лише цю збережену копію з браузера?'))return;await deviceOperation('readwrite',store=>store.delete(row.id));await listDevice();}));buttons.append(open,remove);card.append(buttons);target.append(card);}}
$('#quote-form').addEventListener('submit',event=>{event.preventDefault();guard(()=>{const matches=searchArchiveExactQuote(acceptedArchive(),$('#quote-query').value),target=$('#quote-results');target.replaceChildren();if(!matches.length){target.append(el('p','Точного фрагмента в цій сесії немає.'));return;}for(const match of matches){const card=el('article',undefined,'quote');card.append(el('blockquote',match.text),el('small',`${match.sourceId} → ${match.locator}${match.at?' · '+new Date(match.at).toLocaleString():''}`));target.append(card);}});});
window.addEventListener('beforeunload',event=>{if(session){event.preventDefault();event.returnValue='';}});
guard(()=>{const handoff=takeJourneyHandoff();if(handoff)openArchive(handoff);});
