import { buildBusinessCase } from './business-case.mjs';
import { meetingDirectionsUrl } from './live-location.mjs';

// Fictional fixtures only; no auth, storage, telemetry, GPS or provider requests.
export function summitExample({ need = 'design', asOf = new Date().toISOString().slice(0, 10) } = {}) {
  const person = (id, offer, seeks, goal) => ({ id, is_discoverable: true, updated_at: asOf, brief: {
    goal, offer_tags: [offer], need_tags: [seeks], languages: ['en'], modes: ['exchange'],
    available_from: asOf, available_until: asOf, remote: true,
  } });
  return buildBusinessCase(person('demo-mara', 'design', 'sales', 'Three customer conversations'),
    person('demo-leo', 'sales', need, 'A clearer product offer'), { asOf });
}

const COPY = {
  en: {
    open:'Open app ↗', hero:'Great work.<br>Starts with<br><em>each other.</em>', description:'You bring something valuable.<br>Someone brings what you need.<br>Find the reason to build together.', explore:'Explore the connection <span aria-hidden="true">↗</span>', demoNote:'Interactive demo · fictional profiles · no sign-up', strap:'Less small talk. A clearer first step.', experienceEyebrow:'THE PRODUCT, IN YOUR HANDS', experienceTitle:'A connection<br>with a reason.', experienceLead:"Try the journey. Change the need. See why a conversation makes sense — or why it doesn't.",match:'Discover',terms:'Make it clear',meet:'Meet',synthetic:'SYNTHETIC DEMO · nothing is sent or saved',principles:'Designed for<br><em>both sides.</em>',clarity:'A reason, not a rating.',clarityBody:"See how your declared skills meet each other's needs. No score can promise chemistry or a successful business.",agency:'Your next step. Your choice.',agencyBody:'Review the scope, time and reward together. A suggestion is never permission to send an invitation.',reality:'Start small. Learn for real.',realityBody:'Choose a useful first result. Check what was delivered. Decide whether to keep working together.',closingEyebrow:"YOUR SKILL IS SOMEONE'S NEXT STEP",closing:'What could you<br>build <em>together?</em>',prepare:'Prepare your profile ↗',draftNote:'Profile drafts are available without an account.',releaseSummary:'What is ready in this preview?',releaseBody:"This interactive example uses the product's matching rules. Google Maps opens your selected destination. Live GPS sharing, real two-person acceptance, and production account/database readiness are not demonstrated here. This is a web app preview, not a native Android release.",privacy:'Privacy & terms ↗',
    matchTitle:'Two skills. Two useful outcomes.',matchBody:'Mara designs products. Leo helps businesses meet customers. Try changing what Leo needs.',offers:'OFFERS',seeks:'SEEKS',design:'Product design',sales:'B2B conversations',finance:'Bookkeeping',needLabel:'What does Leo need right now?',good:'Two-way relevance: Mara can help Leo with design. Leo can help Mara with sales. A reason to talk, not a guarantee.',bad:'No two-way fit in this example. Mara has not declared the skill Leo needs. Synera does not invent a match.',next:'Explore the first collaboration →',scopeTitle:'Start with something specific.',scopeBody:'An illustrative scope to discuss. These are not agreed terms or a contract.',scopeA:'Mara → one product-page review',scopeB:'Leo → a customer-conversation plan',effort:'Change Leo’s proposed effort',hours:'hours',balanced:'Both propose 2 hours. Equal time does not establish equal value. Scope, payment and acceptance still need agreement.',unbalanced:'The proposed effort differs. Discuss scope or compensation before either person agrees.',scopeFoot:'In the live app, each person approves the same version separately. Material changes invalidate earlier approvals.',seeMeeting:'See the meeting example →',meetingTitle:'From a conversation to a place.',meetingBody:'Example venue in Zürich. Enter the actual agreed address to open directions. This is not the AI Summit venue.',venue:'Meeting place / full address',mapLabel:'ILLUSTRATION · NOT LIVE GPS OR A STREET MAP',directions:'Walking route in Google Maps ↗',location:'Your position stays with your device and Google Maps. Synera does not request or share GPS here.',navigationHint:'Opens Google Maps. Confirm the destination there. Directions need internet; no ETA is invented.',back:'Restart the example ↺',noPlace:'Enter an in-person meeting address.',
  },
  de: {
    open:'App öffnen ↗',hero:'Gute Arbeit.<br>Beginnt<br><em>miteinander.</em>',description:'Du bringst etwas Wertvolles mit.<br>Jemand hat, was du brauchst.<br>Findet euren Grund, zusammenzuarbeiten.',explore:'Verbindung entdecken <span aria-hidden="true">↗</span>',demoNote:'Interaktive Demo · fiktive Profile · ohne Anmeldung',strap:'Weniger Smalltalk. Ein klarer erster Schritt.',experienceEyebrow:'DAS PRODUKT IN DEINER HAND',experienceTitle:'Eine Verbindung.<br>Ein guter Grund.',experienceLead:'Probiere den Ablauf. Ändere den Bedarf. Entdecke, warum sich ein Gespräch lohnt – oder warum nicht.',match:'Entdecken',terms:'Klären',meet:'Treffen',synthetic:'FIKTIVE DEMO · es wird nichts gesendet oder gespeichert',principles:'Für<br><em>beide Seiten.</em>',clarity:'Ein Grund, keine Bewertung.',clarityBody:'Erkenne, wie eure angegebenen Fähigkeiten den Bedarf der anderen Seite treffen. Kein Wert garantiert den Erfolg.',agency:'Dein nächster Schritt. Deine Wahl.',agencyBody:'Klärt Umfang, Zeit und Gegenleistung gemeinsam. Ein Vorschlag ist nie die Erlaubnis, eine Einladung zu senden.',reality:'Klein anfangen. Echt dazulernen.',realityBody:'Wählt ein nützliches erstes Ergebnis. Prüft die Leistung. Entscheidet dann, ob ihr weiter zusammenarbeitet.',closingEyebrow:'DEIN KÖNNEN IST JEMANDES NÄCHSTER SCHRITT',closing:'Was könntet ihr<br><em>gemeinsam</em> schaffen?',prepare:'Profil vorbereiten ↗',draftNote:'Ein Profilentwurf ist ohne Konto möglich.',releaseSummary:'Was funktioniert in dieser Vorschau?',releaseBody:'Das Beispiel nutzt die Matching-Regeln des Produkts. Google Maps öffnet dein gewähltes Ziel. Live-GPS, echte Bestätigungen zwischen zwei Personen sowie produktive Konten und Datenbank sind hier nicht nachgewiesen. Dies ist eine Web-App-Vorschau, keine native Android-Veröffentlichung.',privacy:'Datenschutz & Bedingungen ↗',
    matchTitle:'Zwei Fähigkeiten. Zwei Ergebnisse.',matchBody:'Mara gestaltet Produkte. Leo bringt Firmen mit Kunden ins Gespräch. Ändere, was Leo braucht.',offers:'BIETET',seeks:'SUCHT',design:'Produktdesign',sales:'B2B-Gespräche',finance:'Buchhaltung',needLabel:'Was braucht Leo gerade?',good:'In beide Richtungen relevant: Mara hilft mit Design, Leo mit Vertrieb. Ein Grund für ein Gespräch, keine Garantie.',bad:'Hier fehlt die gegenseitige Passung. Mara hat die benötigte Fähigkeit nicht angegeben. Synera erfindet keinen Treffer.',next:'Die erste Zusammenarbeit ansehen →',scopeTitle:'Mit etwas Konkretem beginnen.',scopeBody:'Ein Beispiel zur Diskussion. Noch keine vereinbarten Bedingungen und kein Vertrag.',scopeA:'Mara → Prüfung einer Produktseite',scopeB:'Leo → Plan für Kundengespräche',effort:'Leos vorgeschlagenen Aufwand ändern',hours:'Stunden',balanced:'Beide schlagen 2 Stunden vor. Gleiche Zeit bedeutet nicht gleichen Wert. Umfang, Bezahlung und Abnahme müssen geklärt werden.',unbalanced:'Der Aufwand unterscheidet sich. Klärt Umfang oder Vergütung, bevor jemand zustimmt.',scopeFoot:'In der App bestätigt jede Person dieselbe Version separat. Wesentliche Änderungen machen frühere Zustimmungen ungültig.',seeMeeting:'Beispiel für ein Treffen →',meetingTitle:'Vom Gespräch zum Treffpunkt.',meetingBody:'Beispielort in Zürich. Gib die tatsächlich vereinbarte Adresse ein. Dies ist nicht der Veranstaltungsort des AI Summit.',venue:'Treffpunkt / vollständige Adresse',mapLabel:'ILLUSTRATION · KEIN LIVE-GPS ODER STADTPLAN',directions:'Fussweg in Google Maps ↗',location:'Dein Standort bleibt beim Gerät und Google Maps. Synera fragt hier kein GPS ab und teilt es nicht.',navigationHint:'Öffnet Google Maps. Prüfe dort das Ziel. Die Route benötigt Internet; keine erfundene Ankunftszeit.',back:'Beispiel neu starten ↺',noPlace:'Gib die Adresse eines persönlichen Treffens ein.',
  },
  uk: {
    open:'У застосунок ↗',hero:'Сильна робота.<br>Починається<br><em>одне з одного.</em>',description:'У тебе є цінна майстерність.<br>У когось — те, що потрібно тобі.<br>Знайдіть причину працювати разом.',explore:'Відкрити взаємність <span aria-hidden="true">↗</span>',demoNote:'Інтерактивний приклад · вигадані профілі · без входу',strap:'Менше випадкових розмов. Зрозумілий перший крок.',experienceEyebrow:'ПРОДУКТ У ТВОЇХ РУКАХ',experienceTitle:'Знайомство.<br>Зі змістом.',experienceLead:'Пройди сценарій. Зміни потребу. Побач, чому розмова має сенс — або чому ні.',match:'Знайти',terms:'Узгодити',meet:'Зустрітись',synthetic:'ВИГАДАНИЙ ПРИКЛАД · нічого не надсилається й не зберігається',principles:'Створено<br><em>для обох.</em>',clarity:'Причина, а не оцінка.',clarityBody:'Побач, як заявлені навички закривають потреби одне одного. Жоден бал не гарантує хімію чи успішний бізнес.',agency:'Твій крок. Твій вибір.',agencyBody:'Разом перевірте обсяг, час і винагороду. Пропозиція ніколи не є дозволом на відправлення запрошення.',reality:'Почніть із малого. Перевірте на ділі.',realityBody:'Оберіть корисний перший результат. Перевірте виконання. Вирішіть, чи працювати далі.',closingEyebrow:'ТВОЯ МАЙСТЕРНІСТЬ — ЧИЙСЬ НАСТУПНИЙ КРОК',closing:'Що ви могли б<br>створити <em>разом?</em>',prepare:'Підготувати профіль ↗',draftNote:'Чернетку профілю можна створити без акаунта.',releaseSummary:'Що працює в цій версії?',releaseBody:'Приклад використовує правила підбору самого продукту. Google Maps відкриває обране місце. Живий GPS, справжнє погодження двох людей і готовність робочих акаунтів та бази тут не продемонстровані. Це вебверсія для показу, а не реліз нативного Android-застосунку.',privacy:'Правила та приватність ↗',
    matchTitle:'Дві навички. Два результати.',matchBody:'Мара проєктує продукти. Лео допомагає бізнесам говорити з клієнтами. Зміни потребу Лео.',offers:'ПРОПОНУЄ',seeks:'ШУКАЄ',design:'Дизайн продукту',sales:'B2B-розмови',finance:'Бухгалтерія',needLabel:'Що зараз потрібно Лео?',good:'Користь в обидва боки: Мара допоможе з дизайном, Лео — з продажами. Причина поговорити, а не гарантія.',bad:'У цьому прикладі взаємного перетину немає. Мара не заявила потрібну Лео навичку. Synera не вигадує збіг.',next:'Подивитись першу співпрацю →',scopeTitle:'Почніть із конкретного.',scopeBody:'Приклад обсягу для обговорення. Це ще не погоджені умови й не договір.',scopeA:'Мара → один огляд сторінки продукту',scopeB:'Лео → план розмов із клієнтами',effort:'Зміни запропонований час Лео',hours:'години',balanced:'Обидва пропонують 2 години. Однаковий час не означає однакову цінність. Обсяг, винагороду й прийняття ще треба узгодити.',unbalanced:'Запропонований час відрізняється. Обговоріть обсяг або винагороду перед погодженням.',scopeFoot:'У застосунку кожна людина окремо погоджує ту саму версію. Зміна суттєвих умов скасовує попередні погодження.',seeMeeting:'Подивитись приклад зустрічі →',meetingTitle:'Від розмови до місця зустрічі.',meetingBody:'Приклад місця в Цюриху. Введи справжню погоджену адресу для маршруту. Це не адреса AI Summit.',venue:'Місце зустрічі / повна адреса',mapLabel:'ІЛЮСТРАЦІЯ · НЕ ЖИВИЙ GPS І НЕ КАРТА ВУЛИЦЬ',directions:'Пішки через Google Maps ↗',location:'Твоє місце залишається у пристрою й Google Maps. Synera тут не запитує і не передає GPS.',navigationHint:'Відкриється Google Maps. Перевір там місце. Маршрут потребує інтернету; час прибуття не вигадується.',back:'Почати приклад спочатку ↺',noPlace:'Введи адресу особистої зустрічі.',
  },
};

export function installSummit(doc = document) {
  const stage = doc.querySelector('#stage'); if (!stage) return;
  let language = 'en', step = 0, need = 'design', hours = 2, place = 'Zürich Hauptbahnhof, Zürich, Switzerland';
  const t = key => COPY[language][key];
  const el = (tag, text, className) => { const n = doc.createElement(tag); if (text !== undefined) n.textContent = text; if (className) n.className = className; return n; };
  const action = (text, next) => { const b = el('button', text, 'text-button'); b.type = 'button'; b.onclick = () => { step = next; render(); stage.focus(); }; return b; };
  function render() {
    const tabs = [...doc.querySelectorAll('[data-stage]')];
    tabs.forEach((b, index) => { b.setAttribute('aria-selected', String(index === step)); b.tabIndex = index === step ? 0 : -1; });
    stage.setAttribute('aria-labelledby', tabs[step].id); stage.replaceChildren();
    stage.append(el('h3', t(['matchTitle','scopeTitle','meetingTitle'][step])), el('p', t(['matchBody','scopeBody','meetingBody'][step])));
    if (step === 0) {
      const pair = el('div', undefined, 'pair');
      for (const [name, offer, seek] of [['Mara','design','sales'],['Leo','sales',need === 'design' ? 'design' : 'finance']]) {
        const card = el('article', undefined, 'person'), dl = el('dl');
        card.append(el('span', name[0], 'avatar'), el('b', name), el('small', 'Zürich · EN / DE'));
        dl.append(el('dt', t('offers')), el('dd', t(offer)), el('dt', t('seeks')), el('dd', t(seek))); card.append(dl); pair.append(card);
      }
      const label = el('label', t('needLabel')), select = el('select'); select.id = 'demo-need';
      for (const value of ['design','finance']) { const option = el('option', t(value)); option.value = value; select.append(option); }
      select.value = need; select.onchange = () => { need = select.value; render(); doc.querySelector('#demo-need').focus(); }; label.append(select);
      const good = summitExample({ need }).status === 'review_candidate';
      const result = el('div', t(good ? 'good' : 'bad'), 'result' + (good ? '' : ' blocked')); result.id = 'match-result'; result.setAttribute('role','status');
      stage.append(pair, label, result); if (good) stage.append(action(t('next'),1));
    } else if (step === 1) {
      for (const [key, amount] of [['scopeA',2],['scopeB',hours]]) { const row = el('div', undefined, 'scope-row'); row.append(el('span',t(key)),el('strong',amount+' '+t('hours'))); stage.append(row); }
      const label = el('label',t('effort')), select = el('select'); select.id = 'demo-hours';
      for (const amount of [2,12]) { const option = el('option',amount+' '+t('hours')); option.value = String(amount); select.append(option); }
      select.value = String(hours); select.onchange = () => { hours=Number(select.value); render(); doc.querySelector('#demo-hours').focus(); }; label.append(select);
      const result = el('div',t(hours===2?'balanced':'unbalanced'),'result' + (hours===2?'':' blocked')); result.id='effort-result'; result.setAttribute('role','status');
      stage.append(label,result,el('p',t('scopeFoot')),action(t('seeMeeting'),2));
    } else {
      const illustration=el('div',undefined,'map-preview'); illustration.setAttribute('aria-hidden','true'); illustration.append(el('div',undefined,'river'),el('div',undefined,'pin'),el('small',t('mapLabel')));
      const label=el('label',t('venue')), input=el('input'); input.id='demo-venue'; input.type='text'; input.maxLength=240; input.value=place; label.append(input);
      const link=el('a',t('directions'),'primary'); link.id='demo-directions'; link.target='_blank'; link.rel='noopener noreferrer';
      const hint=el('p',t('navigationHint')); hint.id='navigation-status'; hint.setAttribute('role','status');
      const update=()=>{place=input.value; const url=meetingDirectionsUrl(place); if(url){link.href=url;link.removeAttribute('aria-disabled');link.tabIndex=0;}else{link.removeAttribute('href');link.setAttribute('aria-disabled','true');link.tabIndex=-1;} hint.textContent=t(url?'navigationHint':'noPlace');};
      input.addEventListener('input',update); update();
      stage.append(illustration,label,link,hint,el('div',t('location'),'location-note'),action(t('back'),0));
    }
  }
  const translate=()=>{doc.documentElement.lang=language;doc.querySelectorAll('[data-copy]').forEach(n=>{n.innerHTML=t(n.dataset.copy);}); render();}; // Only trusted constants, never user input.
  doc.querySelector('#summit-language').addEventListener('change',event=>{language=Object.hasOwn(COPY,event.target.value)?event.target.value:'en';translate();});
  const tabs=[...doc.querySelectorAll('[data-stage]')];
  tabs.forEach((b,index)=>{b.addEventListener('click',()=>{step=index;render();});b.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(index+1)%3;if(event.key==='ArrowLeft')next=(index+2)%3;if(event.key==='Home')next=0;if(event.key==='End')next=2;if(next!==undefined){event.preventDefault();step=next;render();tabs[next].focus();}});});
  translate();
}
if (typeof document !== 'undefined') installSummit();
