import {test,expect} from '@playwright/test';
import {spawn} from 'node:child_process';
import fs from 'node:fs/promises';
let server,base;
test.beforeAll(async()=>{server=spawn(process.execPath,['web_launch/server.mjs','--demo'],{env:{...process.env,SYNERA_PORT:'0'},stdio:['ignore','pipe','pipe']});base=await new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(new Error('Server timeout')),10000);server.stdout.on('data',chunk=>{out+=chunk;const match=out.match(/http:\/\/127\.0\.0\.1:\d+/);if(match){clearTimeout(timer);resolve(match[0]);}});server.on('exit',()=>{clearTimeout(timer);reject(new Error('Server exit'));});});});
test.afterAll(()=>server?.kill());
async function start(page){await page.goto(base+'/studio.html');await page.locator('[data-step=session]').click();await page.locator('#session-goal').fill('Перевірити перший спільний продукт');await page.locator('#participant-count').selectOption('2');await page.locator('#participant-a').fill('Андрій');await page.locator('#participant-b').fill('Mara');await page.locator('#session-local').check();await page.locator('#session-setup button').click();}
async function outcome(page,text='Обговорили прототип і погодили три розмови з клієнтами.'){await page.locator('[data-step=value]').click();await page.locator('#outcome-facts').fill(text);await page.locator('#outcome-form button').click();}
async function confirmAll(page){await page.locator('[data-confirm=a]').click();await page.locator('[data-confirm=b]').click();}
test('private consent never exposes fit until separate visibility choice; two-way relevance is explained',async({page})=>{
 await page.goto(base+'/studio.html');await page.locator('#fit-consent').check();await page.locator('#fit-form button').click();await expect(page.locator('#fit-results')).toContainText('не відкриває профіль');await expect(page.locator('#fit-results')).not.toContainText('Mara');
 await page.locator('#fit-public').check();await page.locator('#fit-form button').click();const card=page.locator('#fit-results article').filter({hasText:'Mara'});await expect(card).toContainText('Ти отримуєш: Дизайн');await expect(card).toContainText('Ти даєш: Код / автоматизація');
 await page.locator('#fit-consent').uncheck();await page.locator('#fit-form button').click();await expect(page.locator('#fit-results')).not.toContainText('Mara');
});
test('current explicit confirmations gate social draft and revocation/change erase previous draft',async({page})=>{
 await start(page);await outcome(page);await expect(page.locator('#make-social')).toBeDisabled();await page.locator('[data-confirm=a]').click();await expect(page.locator('#make-social')).toBeDisabled();await page.locator('[data-confirm=b]').click();await page.locator('#make-social').click();await expect(page.locator('#social-preview')).toContainText('три розмови');
 await page.locator('[data-confirm=b]').click();await expect(page.locator('#make-social')).toBeDisabled();await expect(page.locator('#copy-social')).toBeDisabled();await expect(page.locator('#social-preview')).not.toContainText('три розмови');
 await page.locator('[data-confirm=b]').click();await outcome(page,'Змінили наступний крок: одна розмова.');await expect(page.locator('#make-social')).toBeDisabled();await expect(page.locator('#outcome-confirmations')).toContainText('Ще без відповіді: Андрій, Mara');
});
test('portable gzip archive roundtrips inert original notes, exact source quotes and escaped share card',async({page})=>{
 await start(page);const note='Мої  точні слова <img src=x onerror="window.attacked=true"> / Zürich 🔥';await page.locator('#note-text').fill(note);await page.locator('#note-form button').click();await expect(page.locator('#session-notes')).toContainText(note);expect(await page.evaluate(()=>window.attacked)).toBeUndefined();
 await outcome(page,'Факт <script>alert(1)</script> & оригінал.');await confirmAll(page);await page.locator('#make-social').click();const cardDownload=page.waitForEvent('download');await page.locator('#download-card').click();const card=await fs.readFile(await(await cardDownload).path(),'utf8');expect(card).toContain('&lt;script&gt;');expect(card).not.toContain('<script>');
 await page.locator('[data-step=memory]').click();const downloadPromise=page.waitForEvent('download');await page.locator('#export-session').click();const file=await(await downloadPromise).path();const envelope=JSON.parse(await fs.readFile(file,'utf8'));expect(envelope.encoding).toBe('gzip-base64');
 await page.locator('#archive-file').setInputFiles(file);await expect(page.locator('#archive-summary')).toContainText('цілісність');page.on('dialog',dialog=>dialog.accept());await page.locator('#accept-archive').click();await expect(page.locator('#session-notes')).toContainText(note);
 await page.locator('[data-step=memory]').click();await page.locator('#quote-query').fill('Мої  точні слова');await page.locator('#quote-form button').click();await expect(page.locator('#quote-results')).toContainText(note);await expect(page.locator('#quote-results')).toContainText('session.notes[');
 envelope.sha256='0'.repeat(64);await page.locator('#archive-file').setInputFiles({name:'tampered.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(envelope))});await expect(page.locator('#value-status')).toContainText('Цілісність');await expect(page.locator('#archive-preview')).toBeHidden();
});
test('device save requires consent and restores exact session after reload without automatic saving',async({page})=>{
 await start(page);await page.locator('#note-text').fill('Збережена тільки за моїм вибором.');await page.locator('#note-form button').click();await page.locator('[data-step=memory]').click();await page.locator('#save-device').click();await expect(page.locator('#value-status')).toContainText('явний вибір');await page.locator('#list-device').click();await expect(page.locator('#device-sessions')).toContainText('немає');
 await page.locator('#device-consent').check();await page.locator('#save-device').click();await expect(page.locator('#value-status')).toContainText('лише у браузері');page.on('dialog',dialog=>dialog.accept());await page.reload();await page.locator('[data-step=memory]').click();await page.locator('#list-device').click();await page.locator('#device-sessions').getByRole('button',{name:'Відкрити',exact:true}).click();await expect(page.locator('#session-notes')).toContainText('Збережена тільки за моїм вибором.');
});
test('new logistics revision removes votes and silent deadline applies only explicit labelled fallback',async({page})=>{
 await start(page);await page.locator('#logistics-place').fill('Zürich HB');await page.locator('#logistics-form button').click();const rows=page.locator('#logistics-votes .member-action');await rows.nth(0).getByRole('button',{name:'Так',exact:true}).click();await rows.nth(1).locator('select').selectOption('yes');await rows.nth(1).getByRole('button',{name:'Зберегти мій резервний вибір'}).click();await expect(page.locator('#logistics-state')).toContainText('без відповіді');
 const deadline=await page.locator('#logistics-deadline').inputValue();await page.evaluate(value=>{const future=new Date(value).getTime()+1000;Date.now=()=>future;},deadline);await expect(page.locator('#logistics-state')).toContainText('попередній резервний вибір');await expect(page.locator('#logistics-state')).toContainText('Участь ще не підтверджено');
 await page.reload();await start(page);await page.locator('#logistics-place').fill('Перше місце');await page.locator('#logistics-form button').click();await page.locator('#logistics-votes .member-action').nth(0).getByRole('button',{name:'Так',exact:true}).click();await page.locator('#logistics-place').fill('Інше місце');await page.locator('#logistics-form button').click();await expect(page.locator('#logistics-state')).toContainText('Андрій: без відповіді');
});
test.describe('installed shell',()=>{test.use({serviceWorkers:'allow'});
 test('dedicated manifest opens Studio and offline reload restores public shell with explicit saved session',async({page,context})=>{
  await start(page);await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>navigator.serviceWorker.controller?.scriptURL.endsWith('/studio-sw.mjs'));const manifest=await(await page.request.get(base+'/studio.webmanifest')).json();expect(manifest.id).toBe('/studio.html');expect(manifest.start_url).toBe('/studio.html');expect(manifest.scope).toBe('/studio');
  await page.locator('[data-step=memory]').click();await page.locator('#device-consent').check();await page.locator('#save-device').click();await expect(page.locator('#value-status')).toContainText('збережено');page.on('dialog',dialog=>dialog.accept());await context.setOffline(true);await page.reload();await expect(page.locator('h1')).toContainText('Твоя сила');await page.locator('[data-step=memory]').click();await page.locator('#list-device').click();await page.locator('#device-sessions').getByRole('button',{name:'Відкрити',exact:true}).click();await expect(page.locator('#active-session-goal')).toContainText('Перевірити перший');
  const cachePaths=await page.evaluate(async()=>{const keys=await caches.keys(),urls=[];for(const key of keys.filter(k=>k.startsWith('synera-studio-'))){for(const request of await(await caches.open(key)).keys())urls.push(new URL(request.url).pathname);}return urls;});expect(cachePaths).toContain('/studio.html');expect(cachePaths).not.toContain('/config.json');expect(cachePaths.some(p=>p.startsWith('/api/'))).toBe(false);
 });
});
