-- NEON REVIEW MIGRATION. NOT APPLIED. Runs after neon/schema.proposal.sql on the SAME project.
-- Generated from supabase/case-state.proposal.sql; do not edit this file by hand.
-- Source SHA256 case=07bc5b5bc813a4c44b9c1f4ba5f75b3ceb8c385845b31f963d67aae3d9ab1e87
begin;
do $$ begin
  if to_regprocedure('public.synera_user_id()') is null or to_regprocedure('public.synera_pilot_member()') is null then raise exception 'Apply neon/schema.proposal.sql first'; end if;
end $$;

do $$ begin
  if to_regclass('public.profiles') is null or to_regclass('public.pilot_consents') is null or to_regclass('public.profile_blocks') is null then
    raise exception 'Apply the real-pilot schema first';
  end if;
  if to_regclass('public.match_cases') is not null or to_regclass('public.match_case_approvals') is not null then
    raise exception 'Inspect existing case schema before applying this proposal';
  end if;
end $$;

-- C0: a profile may carry brief version 2 (pilot modes + mode_details) exactly as normalizeBrief writes it.
create function public.synera_valid_mode_details(d jsonb) returns boolean
language plpgsql immutable security invoker set search_path = '' as $$
declare item text; referral_keys text[] := array['role','benefitTags','sourceDeclared','recipientScopeDeclared','thirdPartyStatus'];
begin
  if jsonb_typeof(d) is distinct from 'object' or not d ?& array['paid_service','referral','hybrid'] or d - array['paid_service','referral','hybrid'] <> '{}'::jsonb then return false; end if;
  if jsonb_typeof(d->'paid_service') is distinct from 'object' or (d->'paid_service') - 'role' <> '{}'::jsonb
    or jsonb_typeof(d->'paid_service'->'role') is distinct from 'string' or d->'paid_service'->>'role' not in ('','buyer','supplier') then return false; end if;
  if jsonb_typeof(d->'referral') is distinct from 'object' or not d->'referral' ?& referral_keys or (d->'referral') - referral_keys <> '{}'::jsonb then return false; end if;
  if jsonb_typeof(d->'referral'->'role') is distinct from 'string' or d->'referral'->>'role' not in ('','introducer','seeker') then return false; end if;
  if jsonb_typeof(d->'referral'->'sourceDeclared') is distinct from 'boolean' or jsonb_typeof(d->'referral'->'recipientScopeDeclared') is distinct from 'boolean' then return false; end if;
  if jsonb_typeof(d->'referral'->'thirdPartyStatus') is distinct from 'string' or d->'referral'->>'thirdPartyStatus' not in ('not_consulted','consented') then return false; end if;
  if jsonb_typeof(d->'referral'->'benefitTags') is distinct from 'array' or jsonb_array_length(d->'referral'->'benefitTags') > 7 then return false; end if;
  for item in select jsonb_array_elements_text(d->'referral'->'benefitTags') loop
    if item is null or item not in ('automation','design','research','sales','video','finance','events') then return false; end if;
  end loop;
  if (select count(distinct v) from jsonb_array_elements_text(d->'referral'->'benefitTags') v) <> jsonb_array_length(d->'referral'->'benefitTags') then return false; end if;
  if jsonb_typeof(d->'hybrid') is distinct from 'object' or (d->'hybrid') - 'components' <> '{}'::jsonb or jsonb_typeof(d->'hybrid'->'components') is distinct from 'array' then return false; end if;
  for item in select jsonb_array_elements_text(d->'hybrid'->'components') loop
    if item is null or item not in ('exchange','paid_service','referral') then return false; end if;
  end loop;
  if (select count(distinct v) from jsonb_array_elements_text(d->'hybrid'->'components') v) <> jsonb_array_length(d->'hybrid'->'components') then return false; end if;
  return true;
exception when others then return false;
end $$;
revoke all on function public.synera_valid_mode_details(jsonb) from public, authenticated;
grant execute on function public.synera_valid_mode_details(jsonb) to authenticated;

create or replace function public.synera_valid_brief(b jsonb) returns boolean
language plpgsql immutable security invoker set search_path = '' as $$
declare k text; item text; v2 boolean; pilot boolean;
  keys text[] := array['version','goal','offer_tags','need_tags','languages','modes','available_from','available_until','remote','max_km','city_code','confidentiality','accepts_confidentiality'];
begin
  if jsonb_typeof(b) is distinct from 'object' then return false; end if;
  v2 := b->'version' = '2'::jsonb;
  if not v2 and b->'version' is distinct from '1'::jsonb then return false; end if;
  if v2 then keys := keys || array['mode_details']; end if;
  if not b ?& keys or b - keys <> '{}'::jsonb then return false; end if;
  foreach k in array array['goal','available_from','available_until','city_code'] loop
    if jsonb_typeof(b->k) is distinct from 'string' then return false; end if;
  end loop;
  if length(b->>'goal') > 240 or b->>'city_code' not in ('','zurich','winterthur','zug','basel','bern') then return false; end if;
  foreach k in array array['remote','confidentiality','accepts_confidentiality'] loop
    if jsonb_typeof(b->k) is distinct from 'boolean' then return false; end if;
  end loop;
  if not (b->'max_km' = any(array['0','25','50','100','300']::jsonb[])) then return false; end if;
  foreach k in array array['offer_tags','need_tags','languages','modes'] loop
    if jsonb_typeof(b->k) is distinct from 'array' then return false; end if;
    if jsonb_array_length(b->k) > (case k when 'languages' then 4 when 'modes' then 5 else 7 end) then return false; end if;
    for item in select jsonb_array_elements_text(b->k) loop
      if k in ('offer_tags','need_tags') and item not in ('automation','design','research','sales','video','finance','events') then return false; end if;
      if k = 'languages' and item not in ('uk','en','de','fr') then return false; end if;
      if k = 'modes' and item not in ('exchange','joint_project','paid_service','referral','hybrid') then return false; end if;
      if item is null then return false; end if;
    end loop;
    if (select count(distinct v) from jsonb_array_elements_text(b->k) v) <> jsonb_array_length(b->k) then return false; end if;
  end loop;
  -- normalizeBrief writes version 2 exactly when a pilot mode is present, and only then mode_details.
  pilot := exists (select 1 from jsonb_array_elements_text(b->'modes') m where m in ('paid_service','referral','hybrid'));
  if pilot is distinct from v2 then return false; end if;
  if v2 and not public.synera_valid_mode_details(b->'mode_details') then return false; end if;
  foreach k in array array['available_from','available_until'] loop
    if b->>k <> '' and ((b->>k) !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' or to_char((b->>k)::date, 'YYYY-MM-DD') <> b->>k) then return false; end if;
  end loop;
  if b->>'available_from' <> '' and b->>'available_until' <> '' and b->>'available_from' > b->>'available_until' then return false; end if;
  return true;
exception when others then return false;
end $$;

-- A paid-service buyer may publish without offering a skill; version 1 keeps the original bilateral rule.
alter table public.profiles drop constraint published_brief_complete,
  add constraint published_brief_complete check (not is_discoverable or (
    length(btrim(brief->>'goal')) > 0 and jsonb_array_length(brief->'languages') > 0 and jsonb_array_length(brief->'modes') > 0
    and brief->>'available_from' <> '' and brief->>'available_until' <> ''
    and (brief->>'city_code' <> '' or brief->'remote' = 'true'::jsonb)
    and case when brief->'version' = '2'::jsonb
      then jsonb_array_length(brief->'offer_tags') > 0 or jsonb_array_length(brief->'need_tags') > 0
      else jsonb_array_length(brief->'offer_tags') > 0 and jsonb_array_length(brief->'need_tags') > 0 end));

-- C1: one case per pair. Version, timestamps and status transitions are server-controlled.
create table public.match_cases (
  case_id text primary key check (case_id ~ '^[A-Za-z0-9_:-]{1,64}$'),
  participant_low uuid not null references public.profiles(id) on delete cascade,
  participant_high uuid not null references public.profiles(id) on delete cascade,
  mode text not null check (mode in ('exchange','paid_service','referral','hybrid')),
  material jsonb not null check (jsonb_typeof(material) = 'object'
    and material ?& array['mode','components','outcomes','trial','compensation','terms']
    and material - array['mode','components','outcomes','trial','compensation','terms'] = '{}'::jsonb
    and material->>'mode' = mode and octet_length(material::text) <= 16384),
  terms_hash text not null check (terms_hash ~ '^[a-f0-9]{64}$'),
  version integer not null default 1 check (version >= 1),
  status text not null default 'open' check (status in ('open','revoked','abandoned')),
  expires_at timestamptz not null,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (participant_low < participant_high),
  check (expires_at <= created_at + interval '90 days'),
  check ((status = 'open') = (closed_at is null))
);
create unique index match_cases_open_pair on public.match_cases(participant_low, participant_high) where status = 'open';
create function public.synera_case_guard() returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    new.version := 1; new.status := 'open'; new.closed_at := null; new.created_at := now(); new.updated_at := now();
    if new.expires_at <= now() then raise exception 'Case already expired'; end if;
    return new;
  end if;
  if old.status <> 'open' then raise exception 'Closed case is immutable'; end if;
  if old.expires_at <= now() then raise exception 'Case expired'; end if;
  if new.case_id <> old.case_id or new.participant_low <> old.participant_low or new.participant_high <> old.participant_high
    or new.created_at <> old.created_at or new.expires_at > old.expires_at then raise exception 'Case identity is immutable'; end if;
  new.updated_at := now();
  if new.status <> 'open' then
    new.closed_at := now(); new.mode := old.mode; new.material := old.material; new.terms_hash := old.terms_hash; new.version := old.version;
    return new;
  end if;
  if new.material is distinct from old.material or new.mode is distinct from old.mode or new.terms_hash is distinct from old.terms_hash then
    if new.terms_hash = old.terms_hash then raise exception 'Material changed without a new hash'; end if;
    -- Older approvals stop being live because they name the previous version and hash.
    new.version := old.version + 1;
  else
    new.version := old.version;
  end if;
  return new;
end $$;
revoke all on function public.synera_case_guard() from public, authenticated;
create trigger match_case_guard before insert or update on public.match_cases for each row execute function public.synera_case_guard();
alter table public.match_cases enable row level security;
revoke all on public.match_cases from public, authenticated;
grant select on public.match_cases to authenticated;
grant insert (case_id, participant_low, participant_high, mode, material, terms_hash, expires_at) on public.match_cases to authenticated;
grant update (mode, material, terms_hash, status, expires_at) on public.match_cases to authenticated;
create policy cases_read on public.match_cases for select to authenticated using ((select public.synera_user_id()) in (participant_low, participant_high));
create policy cases_create on public.match_cases for insert to authenticated with check ((select public.synera_user_id()) in (participant_low, participant_high)
  and exists (select 1 from public.profiles p where p.id = case when participant_low = (select public.synera_user_id()) then participant_high else participant_low end and p.is_discoverable));
create policy cases_update on public.match_cases for update to authenticated
  using ((select public.synera_user_id()) in (participant_low, participant_high) and status = 'open')
  with check ((select public.synera_user_id()) in (participant_low, participant_high));
create policy cases_consent on public.match_cases as restrictive for all to authenticated
using (exists (select 1 from public.pilot_consents c where c.user_id = (select public.synera_user_id()) and c.policy_version = '2026-09-05-pilot-3'))
with check (exists (select 1 from public.pilot_consents c where c.user_id = (select public.synera_user_id()) and c.policy_version = '2026-09-05-pilot-3'));
-- A block stops new material, but either side may still close the case.
create policy cases_unblocked on public.match_cases as restrictive for all to authenticated using (true) with check (status <> 'open'
  or not exists (select 1 from public.profile_blocks b where (b.blocker_id = participant_low and b.blocked_id = participant_high) or (b.blocker_id = participant_high and b.blocked_id = participant_low)));

-- An empty term stays a question: the server refuses approvals of incomplete material, mirroring caseMaterialProblems.
create function public.synera_case_material_complete(m jsonb) returns boolean
language plpgsql immutable security invoker set search_path = '' as $$
begin
  if m->'compensation'->>'status' not in ('agreed_exchange','agreed_money','agreed_none') then return false; end if;
  if m->'components' ? 'paid_service' and m->'compensation'->>'status' <> 'agreed_money' then return false; end if;
  if m->'compensation'->>'status' = 'agreed_money' and (jsonb_typeof(m->'compensation'->'amount_minor') is distinct from 'number'
    or coalesce(m->'compensation'->>'currency', '') !~ '^[A-Z]{3}$' or jsonb_typeof(m->'compensation'->'invoice_required') is distinct from 'boolean') then return false; end if;
  if jsonb_typeof(m->'terms'->'revision_limit') is distinct from 'number' then return false; end if;
  if 'unresolved' in (m->'terms'->>'confidentiality', m->'terms'->>'intellectual_property', m->'terms'->>'cancellation') then return false; end if;
  return coalesce(m->'terms'->>'confidentiality', '') <> '' and coalesce(m->'terms'->>'intellectual_property', '') <> '' and coalesce(m->'terms'->>'cancellation', '') <> '';
exception when others then return false;
end $$;
revoke all on function public.synera_case_material_complete(jsonb) from public, authenticated;
grant execute on function public.synera_case_material_complete(jsonb) to authenticated;

-- C2: an approval names the exact version and hash; only the party itself can insert or withdraw it.
create table public.match_case_approvals (
  id uuid primary key default gen_random_uuid(),
  case_id text not null references public.match_cases(case_id) on delete cascade,
  party_id uuid not null references public.profiles(id) on delete cascade,
  approved_version integer not null check (approved_version >= 1),
  approved_terms_hash text not null check (approved_terms_hash ~ '^[a-f0-9]{64}$'),
  approved_at timestamptz not null default now(),
  withdrawn_at timestamptz
);
create unique index approvals_one_live on public.match_case_approvals(case_id, party_id, approved_version) where withdrawn_at is null;
create index approvals_case on public.match_case_approvals(case_id, approved_version);
create function public.synera_approval_guard() returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if tg_op = 'INSERT' then new.approved_at := now(); new.withdrawn_at := null; return new; end if;
  if old.withdrawn_at is not null then raise exception 'Withdrawn approval is final'; end if;
  if new.case_id <> old.case_id or new.party_id <> old.party_id or new.approved_version <> old.approved_version
    or new.approved_terms_hash <> old.approved_terms_hash or new.approved_at <> old.approved_at then raise exception 'Approval is immutable'; end if;
  new.withdrawn_at := now();
  return new;
end $$;
revoke all on function public.synera_approval_guard() from public, authenticated;
create trigger match_case_approval_guard before insert or update on public.match_case_approvals for each row execute function public.synera_approval_guard();
alter table public.match_case_approvals enable row level security;
revoke all on public.match_case_approvals from public, authenticated;
grant select on public.match_case_approvals to authenticated;
grant insert (case_id, party_id, approved_version, approved_terms_hash) on public.match_case_approvals to authenticated;
grant update (withdrawn_at) on public.match_case_approvals to authenticated;
create policy approvals_read on public.match_case_approvals for select to authenticated using (
  exists (select 1 from public.match_cases c where c.case_id = match_case_approvals.case_id and (select public.synera_user_id()) in (c.participant_low, c.participant_high)));
create policy approvals_create on public.match_case_approvals for insert to authenticated with check (party_id = (select public.synera_user_id())
  and exists (select 1 from public.match_cases c where c.case_id = match_case_approvals.case_id and (select public.synera_user_id()) in (c.participant_low, c.participant_high)
    and c.status = 'open' and c.expires_at > now() and c.version = approved_version and c.terms_hash = approved_terms_hash
    and public.synera_case_material_complete(c.material)));
create policy approvals_withdraw on public.match_case_approvals for update to authenticated
  using (party_id = (select public.synera_user_id())) with check (party_id = (select public.synera_user_id()));
create policy approvals_consent on public.match_case_approvals as restrictive for all to authenticated
using (exists (select 1 from public.pilot_consents c where c.user_id = (select public.synera_user_id()) and c.policy_version = '2026-09-05-pilot-3'))
with check (exists (select 1 from public.pilot_consents c where c.user_id = (select public.synera_user_id()) and c.policy_version = '2026-09-05-pilot-3'));

-- Introduction gate on the server: an invitation needs an open case with both parties' live approvals.
create policy meetings_need_approved_case on public.meeting_requests as restrictive for insert to authenticated with check (
  exists (select 1 from public.match_cases c where c.status = 'open' and c.expires_at > now()
    and c.participant_low = least(sender_id, recipient_id) and c.participant_high = greatest(sender_id, recipient_id)
    and (select count(distinct a.party_id) from public.match_case_approvals a where a.case_id = c.case_id and a.withdrawn_at is null
      and a.approved_version = c.version and a.approved_terms_hash = c.terms_hash and a.party_id in (c.participant_low, c.participant_high)) = 2));

create policy synera_members_only on public.match_cases as restrictive for all to authenticated
  using ((select public.synera_pilot_member())) with check ((select public.synera_pilot_member()));
create policy synera_members_only on public.match_case_approvals as restrictive for all to authenticated
  using ((select public.synera_pilot_member())) with check ((select public.synera_pilot_member()));
do $$ declare r text; t text; begin
  foreach r in array array['anon','anonymous'] loop
    if exists(select 1 from pg_roles where rolname=r) then
      foreach t in array array['match_cases','match_case_approvals'] loop
        execute format('revoke all on public.%I from %I',t,r);
      end loop;
    end if;
  end loop;
end $$;
commit;
