import fs from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { pathToFileURL } from 'node:url';

export function adaptSql(sql) {
  return sql.replaceAll('auth.users', 'neon_auth."user"').replaceAll('auth.uid()', 'auth.user_id()')
    .replace(/\b(user_id|sender_id|recipient_id|blocker_id|blocked_id|reporter_id|reported_id) uuid\b/g, '$1 text')
    .replace(/id uuid primary key references neon_auth\."user"/g, 'id text primary key references neon_auth."user"')
    .replace('declare actor uuid :=', 'declare actor text :=')
    .replace(/, anon\b/g, '').replace(/, service_role\b/g, '');
}
const tables = ['profiles', 'pilot_consents', 'meeting_requests', 'meeting_messages', 'profile_blocks', 'profile_reports'];
const grantsCleanup = `
-- Neon role names can differ from Supabase. Revoke known anonymous roles if present.
do $$ declare r text; t text; begin
  foreach r in array array['anon','anonymous'] loop
    if exists(select 1 from pg_roles where rolname=r) then
      foreach t in array array['profiles','pilot_consents','meeting_requests','meeting_messages','profile_blocks','profile_reports','synera_write_limits','synera_pilot_members'] loop
        execute format('revoke all on public.%I from %I',t,r);
      end loop;
      execute format('revoke all on function public.synera_pilot_member() from %I',r);
      execute format('revoke all on function public.synera_limit_writes() from %I',r);
    end if;
  end loop;
end $$;
`;
const membership = `
-- This operator-owned admission list is deliberately unreadable to API users.
create table public.synera_pilot_members (
  email text primary key check (email=lower(btrim(email)) and length(email) between 3 and 254),
  created_at timestamptz not null default now()
);
alter table public.synera_pilot_members enable row level security;
revoke all on public.synera_pilot_members from public, authenticated;
-- A narrow boolean authorization boundary: no arguments, caller from verified JWT,
-- no arbitrary lookup, no profile fields returned, fixed empty search_path.
create function public.synera_pilot_member() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from neon_auth."user" u join public.synera_pilot_members m on m.email=lower(u.email)
    where u.id=(select auth.user_id()) and u."emailVerified"=true
  );
$$;
revoke all on function public.synera_pilot_member() from public, authenticated;
grant execute on function public.synera_pilot_member() to authenticated;
${tables.map(t => `create policy synera_members_only on public.${t} as restrictive for all to authenticated
  using ((select public.synera_pilot_member())) with check ((select public.synera_pilot_member()));`).join('\n')}
`;
export function generateSchema(baseline, proposal) {
  if (!baseline.includes('create table public.profiles') || !proposal.includes('create table public.synera_write_limits')) throw new Error('Schema source changed; review before generating');
  const body = [baseline, proposal].map(source => source.slice(source.indexOf('begin;') + 6, source.lastIndexOf('commit;'))).join('\n');
  const hashes = [baseline, proposal].map(source => createHash('sha256').update(source).digest('hex'));
  const result = `-- NEON REVIEW PROPOSAL. NOT APPLIED. New EMPTY Synera project only.
-- Generated from the existing SQL contract; do not edit this file by hand.
-- Source SHA256 baseline=${hashes[0]} proposal=${hashes[1]}
begin;
do $$ begin
  if to_regclass('neon_auth."user"') is null or to_regprocedure('auth.user_id()') is null then raise exception 'Enable Neon Auth and Data API first'; end if;
  if to_regclass('public.profiles') is not null then raise exception 'Target is not empty; inspect before migration'; end if;
  if (select data_type from information_schema.columns where table_schema='neon_auth' and table_name='user' and column_name='id') is distinct from 'text' then raise exception 'Inspect Neon identity type before migration'; end if;
end $$;
revoke create on schema public from public, authenticated;
grant usage on schema public to authenticated;
${adaptSql(body)}
${membership}
${grantsCleanup}
-- No email addresses are seeded. Add explicitly invited, verified participants as owner.
commit;
`;
  if (/auth\.users|auth\.uid\(\)|(?:sender_id|recipient_id|user_id|blocker_id|blocked_id|reporter_id|reported_id) uuid/.test(result)) throw new Error('Incomplete identity migration');
  return result;
}

export function generateAcceptance(source) {
  let sql = adaptSql(source).replace(/--[^\n]*\n/g, '');
  const start = sql.indexOf('insert into neon_auth."user"(id)');
  const end = sql.indexOf('insert into public.profiles(');
  if (start < 0 || end < start) throw new Error('Acceptance fixture changed');
  sql = sql.slice(0, start) + `insert into neon_auth."user"(id,name,email,"emailVerified","createdAt","updatedAt") values
('11111111-1111-4111-8111-111111111111','Acceptance A','a@synera-acceptance.example',true,now(),now()),
('22222222-2222-4222-8222-222222222222','Acceptance B','b@synera-acceptance.example',true,now(),now()),
('33333333-3333-4333-8333-333333333333','Acceptance C','c@synera-acceptance.example',true,now(),now()),
('44444444-4444-4444-8444-444444444444','Uninvited','uninvited@synera-acceptance.example',true,now(),now());
insert into public.synera_pilot_members(email) values ('a@synera-acceptance.example'),('b@synera-acceptance.example'),('c@synera-acceptance.example');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"44444444-4444-4444-8444-444444444444","role":"authenticated"}',true);
do $$ begin
  if auth.user_id() is distinct from '44444444-4444-4444-8444-444444444444' then raise exception 'JWT fixture context unsupported; inspect auth.user_id without replacing it'; end if;
  if public.synera_pilot_member() then raise exception 'Uninvited member passed'; end if;
  begin
    insert into public.pilot_consents(user_id,policy_version,terms_accepted,privacy_acknowledged)
      values (auth.user_id(),'2026-09-05-pilot-3',true,true);
    raise exception 'Uninvited user entered pilot';
  exception when insufficient_privilege then null; end;
  begin perform 1 from public.synera_pilot_members; raise exception 'Invited emails leaked'; exception when insufficient_privilege then null; end;
end $$;
reset role;
` + sql.slice(end);
  const anonStart = sql.indexOf('set local role anon;');
  const anonEnd = sql.indexOf("select 'PASS:", anonStart);
  if (anonStart < 0 || anonEnd < anonStart) throw new Error('Anonymous acceptance changed');
  sql = sql.slice(0, anonStart) + `do $$ declare r text; t text; begin
  foreach r in array array['anon','anonymous'] loop
    if exists(select 1 from pg_roles where rolname=r) then
      foreach t in array array['profiles','pilot_consents','meeting_requests','meeting_messages','profile_blocks','profile_reports','synera_pilot_members','synera_write_limits'] loop
        if has_table_privilege(r,'public.'||t,'SELECT,INSERT,UPDATE,DELETE') then raise exception 'Anonymous table grants remain'; end if;
      end loop;
    end if;
  end loop;
end $$;
` + sql.slice(anonEnd);
  return '-- NOT RUN. Neon-only transactional acceptance. Requires exact approval. Always ROLLBACK.\n-- This tests RLS with fixtures, not real login, email delivery, or an actual phone.\n' + sql;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const [base, proposal, acceptance] = await Promise.all(['schema.sql', 'real-pilot.proposal.sql', 'real-pilot.acceptance.sql'].map(file => fs.readFile(new URL('../supabase/' + file, import.meta.url), 'utf8')));
  await fs.writeFile(new URL('./schema.proposal.sql', import.meta.url), generateSchema(base, proposal));
  await fs.writeFile(new URL('./acceptance.sql', import.meta.url), generateAcceptance(acceptance));
  console.log(JSON.stringify({ generated: ['neon/schema.proposal.sql', 'neon/acceptance.sql'], applied: false }));
}
